apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "oren-kv"
    objects: |
      array:
        - |
          objectName: secret1
          objectType: secret
    tenantID: <tenantID>
