replicaCount: 1

image:
  repository: orenacr.azurecr.io/hello
  tag: 0.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  pathType: Prefix
